import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Image from "next/image";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-gray-50 text-gray-900`}
      >
        <nav className="w-full bg-white shadow sticky top-0 z-50 flex items-center justify-between px-4 py-2 md:px-8">
          {/* LOGO PLACEHOLDER */}
          <div className="flex items-center">
            <div className="w-10 h-10 bg-gray-200 rounded mr-3 flex items-center justify-center">
              <Image
                src="https://media-exp1.licdn.com/dms/image/C510BAQEfLyZ-XY1_TA/company-logo_200_200/0/1580537385561?e=2159024400&v=beta&t=dn3gjEL0HEpowQkZDSwj6PrlW4YfxqIOO89AE5GULxI"
                alt="Apollo Doctors Logo"
                width={40}
                height={40}
                className="rounded"
              />
              {/* <span className="text-xs text-gray-400">Logo</span> */}
            </div>
            <span className="font-bold text-lg tracking-tight">Apollo Doctors</span>
          </div>
          <div className="hidden md:flex gap-6">
            {/* Add nav links here if needed */}
          </div>
        </nav>
        <main className="max-w-5xl mx-auto px-2 md:px-0">
          {children}
        </main>
      </body>
    </html>
  );
}
